FROM python

WORKDIR /app

COPY . /app

CMD [ "python", "bmi.py" ]


#docker build .
#docker run -it <image>
#docker stop <container>
#docker run --name python-app -it <image>
#docker stop python-app
#docker rm python-app
#docker rmi <image>
#docker build -t pytho-app:test .
#docker run --name python-app --rm -it pytho-app:test